repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: no-commit-to-branch
        args: [ --branch=main, --branch=dev, --branch=test ]

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        entry: flake8
        additional_dependencies: [ "flake8-pyproject==1.2.3" ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: [ "--config-file=./pyproject.toml" ]
        additional_dependencies: ["pydantic==2.9.2", "fastapi==0.115.5"]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: ./.venv/bin/pytest tests
        language: system
        types: [ python ]
        pass_filenames: false
        always_run: true
